#kubectl apply -f doom_manifest.yaml
#kubectl port-forward service/doom-game-service 9090:8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom-game
  namespace: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doom-game
  template:
    metadata:
      labels:
        app: doom-game
    spec:
      containers:
      - name: doom-game
        image: callumhoughton22/doom-in-docker:0.1
        ports:
        - containerPort: 8080
        env:
        - name: DISPLAY
          value: ":0"
---
apiVersion: v1
kind: Service
metadata:
  name: doom-game-service
  namespace: game
spec:
  selector:
    app: doom-game
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
